name: C/C++ CI

on:
  push:
    branches: [ master, feat/ros-build]
  pull_request:
    branches: [ master ]

jobs:
  build-native:
    runs-on: ubuntu-latest
    container:
      image: cquesnel/ros
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'catkin_ws/src/HiveMind'
      - name: build
        run: |
          cd catkin_ws
          . /opt/ros/$ROS_DISTRO/setup.sh
          catkin_make

      # Tests, check-format and doc are run on native build
      - name: tests
        run: |
          cd catkin_ws
          . /opt/ros/$ROS_DISTRO/setup.sh
          . ./devel/setup.sh
          cd build/HiveMind
          ctest -V

      - name: check-format
        run: |
          cd catkin_ws
          . /opt/ros/$ROS_DISTRO/setup.sh
          . ./devel/setup.sh
          catkin_make check-format

      # Verifies that the doc is built
      - name: doc
        run: |
          cd catkin_ws
          . /opt/ros/$ROS_DISTRO/setup.sh
          . ./devel/setup.sh
          catkin_make doc

  build-stm32:
    runs-on: ubuntu-latest
    container:
      image: cquesnel/ros
    steps:
    - uses: actions/checkout@v2

    - name: prepare
      run: |
        mkdir -p build
        cd build
        cmake -D CMAKE_TOOLCHAIN_FILE=../cmake/stm32_f429zi_gcc.cmake ..

    - name: build
      run: |
        cd build
        make -j
