name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-noetic:
    runs-on: ubuntu-20.04
    container:
      image: swarmus/embedded
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'catkin_ws/src/HiveMind'
      - name: build
        run: |
          cd catkin_ws
          . /opt/ros/$ROS_DISTRO/setup.sh
          rosdep update
          apt update
          rosdep install --from-paths src --ignore-src -r -y
          catkin_make -DENABLE_ERROR_ON_MISSING_TOOL=ON -DENABLE_WARNINGS_AS_ERROR=ON -DENABLE_WARNINGS=ON -DENABLE_CLANG_TIDY_CHECK=ON -DENABLE_TESTS=ON
      # Tests, check-format and doc are run on native build
      - name: tests
        run: |
          cd catkin_ws
          . /opt/ros/$ROS_DISTRO/setup.sh
          . ./devel/setup.sh
          cd build/HiveMind
          ctest -V

      - name: check-format
        run: |
          cd catkin_ws
          . /opt/ros/$ROS_DISTRO/setup.sh
          . ./devel/setup.sh
          catkin_make check-format

      # Verifies that the doc is built
      - name: doc
        run: |
          cd catkin_ws
          . /opt/ros/$ROS_DISTRO/setup.sh
          . ./devel/setup.sh
          catkin_make doc

  build-stm32:
    runs-on: ubuntu-latest
    container:
      image: swarmus/embedded
    steps:
    - uses: actions/checkout@v2

    - name: prepare
      run: |
        mkdir -p build
        cd build
        cmake -D CMAKE_TOOLCHAIN_FILE=../cmake/stm32_f429zi_gcc.cmake -DENABLE_ERROR_ON_MISSING_TOOL=ON -DENABLE_WARNINGS_AS_ERROR=ON -DENABLE_WARNINGS=ON -DENABLE_CLANG_TIDY_CHECK=ON ..

    - name: build
      run: |
        cd build
        make -j

  # Verfies that we can still build on melodic
  build-melodic:
    runs-on: ubuntu-20.04
    container:
      # Container of ros with ubuntu 18.04
      image: swarmus/ros-melodic
    steps:
    - uses: actions/checkout@v2
      with:
        path: 'catkin_ws/src/HiveMind'
    - name: build
      run: |
        cd catkin_ws
        . /opt/ros/$ROS_DISTRO/setup.sh
        catkin_make 
